config/routes.rb
TwitterExperimentOne::Application.routes.draw do
  devise_for :users

  root :to => "tweets#index"
  resources :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :body

  validates :body, :presence => true
  validates :body, :length => {:maximum => 140}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :find_tweet, :only => [:edit, :update, :show, :destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(params[:tweet])
    if @tweet.save
      flash[:notice] = "You just created a new tweet."
      redirect_to @tweet
    else
      flash[:notice] ="Could not create tweet."
      render :action => "new"
    end
  end

  def show
    #
  end

private
  def find_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <div class = "row">
      <% flash.each do |key, value| %>
        <div class="flash" id="<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <nav>
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </nav>
      <%= yield %>
    </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <%= f.error_messages %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>

<% end %>

app/views/tweets/index.html.erb
<div class="panel large-8 column">
  <h2>Tweets!</h2>
  <% @tweets.each do |tweet| %>
    <%= link_to tweet.body, tweet %>
  <% end %>
  <%= link_to "New Tweet", new_tweet_path %>
</div>

app/views/tweets/new.html.erb
<div class="panel large-8 column">
  <h2>New Tweet!</h2>
  <%= render "form" %>
</div>

app/views/tweets/show.html.erb
<div class="panel large-8 column">
  <h2>Tweet:</h2>
  <%= @tweet.body %>

</div>